### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by xmcodings**
hi guys i think its time to merge to master

please review!!

### CODE REVIEW

**Comment by sihan827** [comment]
this is our first MVP
good job guys~

**Review by sihan827 — COMMENTED** [review]
All file is good! I think we can merge this to master

**Comment by J00nCh1** [comment]
Found no problem to merge. Great job everyone!

**Review by jeokjoong — COMMENTED** [review]
Found no problem to merge. Great job everyone!

**Review by sw0082 — APPROVED** [review]

**Pull request merged**
